#!/bin/bash
#pacget script
# 本脚本来自于http://www.linuxsir.org/bbs/thread285924.html
# 用于pacman的下载脚本

rm -f *.aria2
cachedir=/var/cache/pacman/pkg
file=`echo $1|awk -F '/' '{ print $NF }'`
echo Downloading: $file|sed 's,/,,'
repo=`echo $1|awk -F '/' '{x=NF-3 } { print  $x }'`
echo repo: $repo
if [[ $2 = *.db.tar.gz.part || $repo = "testing" ]]; then
       echo "(using one mirror)"
       mirrors=$1
else
       if [ -f /etc/pacman.d/$repo ]; then
       mirrors=`sed -n 's/^Server = //; s,$,/'"$file"', ; /^ftp/p; /^http/p' /etc/pacman.d/$repo`
       fi
fi

aria2c -t20 -m2 -l /var/log/pacget.log $mirrors -o $file.pacget
if [ -f $cachedir/$file.pacget.aria2 ]; then
      rm $cachedir/$file.pacget $cachedir/$file.pacget.aria2
      exit 0
fi

mv $file.pacget $2
exit 0  